### ISSUE TITLE
export perspective opens a blank window

### ISSUE THREAD

**Issue by CatherineH** [ros-visualization/rqt#102]
When I try to export my perspective, I get a blank window. Here's a screenshot:

![export_perspective_not_rendering](https://cloud.githubusercontent.com/assets/1953328/7703953/53e2b454-fe09-11e4-816b-50f77f7a36d8.png)

I'm using Ubuntu 14.04, and I installed rqt_gui from ros-indigo-desktop-full.

**Comment by dirk-thomas** [comment]
The code is only invoking `QFileDialog.getSaveFileName` (https://github.com/ros-visualization/qt_gui_core/blob/22f5c031ae97ba9ad88c0974f8dbf7bd2ae6b8ea/qt_gui/src/qt_gui/perspective_manager.py#L346). Therefore I don't think this can be a bug in rqt but more likely a rendering glitch in Qt itself.

Do you still have this problem on an up-to-date system?

**Comment by shashwatak** [comment]
Hi, I am having an identical problem, any word on what this is or how to resolve it?

Is there another way to export perspectives?

**Comment by dirk-thomas** [comment]
I will close this ticket and mark it with "wontfix" since `rqt` can't do anything to address this afaik.
