### ISSUE TITLE
Improper Rendering of text in rqt

### ISSUE THREAD

**Issue by sidcode** [ros-visualization/rqt#103]
The attached figure - ![rqt_formatting](https://cloud.githubusercontent.com/assets/3395598/7898610/b3a424d2-0722-11e5-8229-fc9b9e4dab09.png)

ROS Indigo Version 1.11.13
Ubuntu 14.04
rqt_tf_tree  0.4.1
rqt_graph 0.3.11

The problem of Text rendering persists in all rqt applications for me.

**Comment by dirk-thomas** [comment]
Please open the ticket in the issue tracker of the repository where `rqt_tf_tree` is in (https://github.com/ros-visualization/rqt_robot_plugins) and close this.

If a similar problem exists in `rqt_graph` please consider filling a separate issue in https://github.com/ros-visualization/rqt_common_plugins (with its own screenshot).

**Comment by sidcode** [comment]
Thanks, I'll do that.
