### ISSUE TITLE
additional plugin instances when switching the perspective from the command line

### ISSUE THREAD

**Issue by thunderbug1** [ros-visualization/rqt#108]
I just created two simple perspectives "a" and "b" and added a simple plugin instance to each of them ( for example plot and image view ).
When I use the command line command to switch between them, I get an additional plugin instance with every time I switch the perspective. These instances cannot even be closed by clicking the X.
It does not happen when I use the GUI to change the perspective.

I am running ubuntu 14.04 with ROS indigo if that matters.

**Comment by dirk-thomas** [comment]
Thank you for the report. I am sorry that it took quite a while to find time to look into this problem. And then the source of the problem was not that easy to identify :wink:. I finally came up with a fix for this bug: ros-visualization/qt_gui_core#80
