### ISSUE TITLE
when run rqt in terminal meet core dump

### ISSUE THREAD

**Issue by DavidHan008** [ros-visualization/rqt#116]
when I want to run:  rosrun rqt_graph rqt_graph and find core dump. I find all of rqt plugs is not work.

**Comment by dirk-thomas** [comment]
Please provide enough information that others can try to help you. In this case:

* What platform are you on?
* Have you installed binary package or compiled from source (in both cases: which versions?)?
* Please run the application with `gdb` to provide a stacktrace how it exactly fails.

**Comment by dirk-thomas** [comment]
Closing for now due to lack of response. Please feel free to comment with the requested information and the ticket can be reopened.
