### ISSUE TITLE
rqt perspective saves window size in a resolution dependent manner

### ISSUE THREAD

**Issue by piyushk** [ros-visualization/rqt#123]
I believe that window resolution is being saved dependent on the current window size. It would make much more sense to save the window size in absolute pixels instead.

Steps to reproduce:
1. Run a fresh rqt gui instance with `--clear-config`
2. Add 2 plugins (Image view and Robot Steering), and resize the window to roughly a quarter of your screen. My screen looks as follows (dual screen at 1920 x 1080):
![1920x1080](https://user-images.githubusercontent.com/1686279/28544167-fe9281a2-7087-11e7-8316-c542236df944.png)
3. Quit rqt so that whatever config you had was saved as the default config.
4. Re-run rqt normally and ensure that the layout exactly matches prior to quitting the last time.
5. Change your screen resolution to something smaller (I changed mine to 1368 x 768).
6. Re-run rqt.
![1366x768](https://user-images.githubusercontent.com/1686279/28544166-fe7c662e-7087-11e7-8917-f87b130c0daa.png)

Here, the window should have gotten bigger, however it is still roughly a quarter of my screen. This is problematic, as individual plugins in more complex dashboards shift in weird ways as font size changes.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/qt_gui_core#98
