### ISSUE TITLE
rqt_plot cannot receive any data

### ISSUE THREAD

**Issue by Herschelpu** [ros-visualization/rqt#135]
I tried to plot my data into rqt_plot to get the figure. However rqt suddenly return zeros for all of my data. I checked the data by using "rostopic echo" command and it actually has non-zero data stream. I created a node that only had one publisher publishing a non-zero number but also got zero plot. I also tried to reinstall this ros-kinetic-rqt but still not working..... so is there anyone know what happen to my rqt plot?     
![image](https://user-images.githubusercontent.com/25504358/43520327-6a0ea0d2-958a-11e8-8248-ca2591fe30e2.png)

**Comment by dirk-thomas** [comment]
I tried to publish a number using the command line tools:

```
rostopic pub /number std_msgs/Int32 "{data: 42}" -r 10
```

And after selecting the topic `/number` in the `rqt_plot` gui the line is plotted at the expected value.

**Comment by dirk-thomas** [comment]
Closing due to no responses.
