### ISSUE TITLE
(rqt_gui) protect itself from severe error arising from plugins

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#14]
Currently, if a severe error (eg. segfault) occurs in a plugin, the entire rqt_gui crashes.

Although I have no idea for now how feasible to implement a feature to avoid this issue, I think it's reasonable enhancement request especially b/c rqt framework is open to users who want to make their own plugins where assuring quality for each plugin is impossible.

**Comment by dirk-thomas** [comment]
Impossible to achieve. If plugins are considered unstable and likely to segfault you should use the `--multi-process` mode to run them in separate processes.
