### ISSUE TITLE
ROS2 callback execution groups

### ISSUE THREAD

**Issue by mlautman** [ros-visualization/rqt#168]
We may want to add a `ReentrantCallbackGroup` to the plugin context so that multiple plugins can have callbacks serviced simultaneously.

**Comment by brawner** [comment]
From @dirk-thomas's comment (https://github.com/ros-visualization/rqt/pull/167#discussion_r240293932), this does not sound like a desirable fix.

From Dirk:
> A `ReentrantCallbackGroup` implies that the very same callback can be called multiple times (not that "multiple plugins can have callbacks serviced simultaneously"). Usually that is undesired and most callback function won't be written in a way to support that.
