### ISSUE TITLE
Calls to qDebug are causing an error on Oneiric

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#17]
It states that qDebug arguments must be strings not Unicode.

Confirmed as occurring on most plugins (rqt_console excluded)

This results in a failure to load the plugin

Traceback (most recent call last):
  File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/main.py", line 277, in message_handler
    if type_ == QtDebugMsg and self._options.verbose:
  File "/opt/ros/groovy/lib/python2.7/dist-packages/qt_gui/plugin_manager.py", line 144, in load_plugin
    qDebug('PluginManager.load_plugin(%s, %s)' % (plugin_id, str(serial_number) if serial_number is not None else ''))
TypeError: 'qDebug' called with wrong argument types:
  qDebug(unicode)
Supported signatures:
  qDebug(str)

**Comment by dirk-thomas** [comment]
Issue could not be reproduce. Please reopen with version numbers of the relevant packages and step-by-step instructions when it reappears.

**Comment by dirk-thomas** [comment]
Reproduced with PySide only. Above mentioned change fixed the issue.
