### ISSUE TITLE
rviz plugin crashes inside rviz when run on groovy

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#18]
error documented in issue ros-visualization/rviz#553

**Comment by DorianScholz** [comment]
it works fine for me on precise, with fuerte.
may be groovy specific?

**Comment by ablasdel** [comment]
Yes I forgot to mention it is a groovy specific crash. I have tagged it now.

**Comment by ablasdel** [comment]
This issue is most likely a duplicate of #16 I am going to close this. 
I will re-open it if it reoccurs after we have fixed #16
