### ISSUE TITLE
[crystal-devel] rqt_py_common test failing

### ISSUE THREAD

**Issue by jacobperron** [ros-visualization/rqt#192]
Linux CI: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6566)](https://ci.ros2.org/job/ci_linux/6566/)

```
build/rqt_py_common/test_results/rqt_py_common/rqt_py_common.xunit.xml: 12 tests, 0 errors, 1 failure, 0 skipped
- rqt_py_common.test.test_rqt_common_unit.TestMessageTreeModel test_path_names (test/test_rqt_common_unit.py:39)
  <<< failure message
    AttributeError: 'NoneType' object has no attribute '_path'
  >>>
```

**Comment by jacobperron** [comment]
@dirk-thomas I think this can be close?

**Comment by dirk-thomas** [comment]
Interesting, the reference in the description of the merged PR should have done that automatically...

*Update:* nvm, since it targeted the `crystal-devel` branch instead of the default one it didn't.

Thanks for pointing it out - closing it manually.
