### ISSUE TITLE
Malformed message_type rqt ROS2

### ISSUE THREAD

**Issue by skucheria** [ros-visualization/rqt#197]
**- Operating System:**
Ubuntu 18.04
**- Installation type:**
from source
**- DDS implementation:**
RTI Connext
**- Client library (if applicable):**
rqt

Receiving "malformed message_type" error on message types in rqt when attempting to use rqt_plot or topic monitor. 
Ex:

```
[ERROR] [get_message_class]: Malformed message_type: std_msgs/msg/String
TopicInfo.__init__(): topic "/robot_description": can not get message class for type "std_msgs/msg/String"
```

**Comment by dirk-thomas** [comment]
This should be resolved on the latest HEAD on the `crystal-devel` branch. Please try it again to confirm that it is fixed for you.

**Comment by dirk-thomas** [comment]
I will go ahead and close this assuming the problem has already been resolved. Please feel free to comment on the closed ticket and if necessary it can be reopened.
