### ISSUE TITLE
[noetic] Cannot launch rqt_reconfigure standalone

### ISSUE THREAD

**Issue by doisyg** [ros-visualization/rqt#226]
Loading the plugin from rqt works, however, starting the tool directly with `rosrun rqt_reconfigure rqt_reconfigure ` crashes:

> Traceback (most recent call last):
>   File "/opt/ros/noetic/lib/rqt_reconfigure/rqt_reconfigure", line 5, in <module>
>     from rqt_gui.main import Main
>   File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/main.py", line 40, in <module>
>     from rospkg.rospack import RosPack
> ImportError: No module named rospkg.rospack
>

**Comment by cottsay** [comment]
You should be able to work around this issue by ensuring that the Python 3 module `rospkg` is installed.

**Comment by doisyg** [comment]
Solved it by using python alternative and be sure that `$ python -V` outputs `Python 3.8.2`
