### ISSUE TITLE
[ROS2] rqt: CompositePluginProvider.discover() could not discover plugins

### ISSUE THREAD

**Issue by flu0r1ne** [ros-visualization/rqt#253]
I'm on `5.12.10-arch1-1` archlinux and receive the following error when I try to start `rqt`:

```
CompositePluginProvider.discover() could not discover plugins from provider "<class 'rqt_gui.rospkg_plugin_provider.RospkgPluginProvider'>":
Traceback (most recent call last):
  File "/opt/ros2/foxy/lib/python3.9/site-packages/qt_gui/composite_plugin_provider.py", line 57, in discover
    plugin_descriptors = plugin_provider.discover(discovery_data)
  File "/opt/ros2/foxy/lib/python3.9/site-packages/rqt_gui/ros_plugin_provider.py", line 68, in discover
    plugin_descriptors += self._parse_plugin_xml(package_name, plugin_xml)
  File "/opt/ros2/foxy/lib/python3.9/site-packages/rqt_gui/ros_plugin_provider.py", line 128, in _parse_plugin_xml
    for library_el in root.getiterator('library'):
AttributeError: 'ElementTree' object has no attribute 'getiterator'
```

If I use `rqt_graph` I get a `qt_gui_main() found no plugin matching "rqt_graph.ros_graph.RosGraph"
try passing the option "--force-discover"`.

Any recommendations? Forcing discovery did not fix the issue.

**Comment by clalancette** [comment]
It's not clear how this installation was done on Arch.  That would be good information to provide.

However, Arch is not one of our supported platforms.  So I'll suggest that you open up a question on https://answers.ros.org; you may be able to get the attention of people who use Arch and get some better answers.

I'm going to close this one out.
