### ISSUE TITLE
noetic release missing

### ISSUE THREAD

**Issue by v4hn** [ros-visualization/rqt#259]
https://github.com/ros-visualization/rqt/pull/241 was merged, but the package was not newly released into noetic. So the package is still broken in noetic and requires users to build from source... :(

Could you please trigger a quick release to get this fixed?

**Comment by jacobperron** [comment]
Sorry for the delay. We overlooked this issue. I've made a new release for Noetic: https://github.com/ros/rosdistro/pull/32529

**Comment by v4hn** [comment]
thanks!
