### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by fcolecumberri** [ros-visualization/rqt#281]
I know this is a ROS package and it uses the same license as the rest of ROS (which I think is Apache V2).

However if someone that doesn't know that arrive to this GitHub page, they will not know under which license this project is.

**Comment by clalancette** [comment]
Yes, good point (though the license on this code is BSD, not Apache 2.0).  See #282 which should fix this.

**Comment by ahcorde** [comment]
Already fixed, see comment above and related PR
