### ISSUE TITLE
rqt_robot_monitor is not displaying all errors and stale elements in the error pane

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#31]

**Comment by 130s** [comment]
Should be fixed in 5e6a92bacb8a7cd04a020a9df5257fca5630d95c. Will wait for confirmation by others.

**Comment by ablasdel** [comment]
I can confirm I saw stale items and errors show up in the top pane yesterday. Feel free to close the issue if you have fixed it. No need to wait for confirmation from a second party. We can just reopen the ticket if we find the bug again.
