### ISSUE TITLE
rqt_robot_monitor is not displaying icons on some computers

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#32]
This issue is related to the Tango icon set (which we use as a default for not compliant icon themes) is missing the icons that were used to display states.

**Comment by 130s** [comment]
Should be fixed in cfe85b82819f05d4ee5e415c3916f060559acdcb but will wait for confirmation.

**Comment by ablasdel** [comment]
I looked at the tango icon set and the new theme icons exist so this is solved. If it isn't we will reopen upon confirmation.
