### ISSUE TITLE
Crashes on startup: terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by hershwg** [ros-visualization/rqt#35]
I just apt-get installed rqt for groovy:

```
Setting up ros-groovy-rqt (0.1.4-s1354065869~precise)
```

Result was disappointing:

```
hersh@spf$ rosrun rqt_gui rqt_gui 
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted
```

Trying again clearing my config:

```
hersh@spf$ rosrun rqt_gui rqt_gui --clear-config
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted
```

**Comment by ablasdel** [comment]
We are planning to release a new version soon. But just to be sure can you send me the contents of your ~/.config/ros.org/rqt_gui.ini file?

**Comment by dirk-thomas** [comment]
The ini file won't help. A stacktrace would provide more information where this string operation fails.

**Comment by dirk-thomas** [comment]
Turned out it was an older version - works with current state.
