### ISSUE TITLE
rqt_plot doesn't load MatPlot in pyside

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#38]
running

```
rosrun rqt_gui rqt_gui -b pyside
```

and loading rqt_plot causes this warning:

```
No usable plot type found. Install at least one of: PyQtGraph, MatPlotLib or Python-Qwt5
```

When running in pyqt MatPlot loads successfully and can graph.

rqt latest from source 9753cff2a9fe645c2fb8c91c79a8ef4c02bdb8a5
ros-groovy-qt-gui-core 0.2.6
python-matplotlib 1.1.1~rc1+git20120423-0ubuntu1

**Comment by dirk-thomas** [comment]
The matplot requires at PySide > 1.1.0.
