### ISSUE TITLE
rqt_gui (pyqt) segfaults before opening its window

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#39]
The following segfaults occurs http://pastebin.com/D8Mg1MRC (includes catkin_make process and stuff).

So far with pyside segfault hasn't happened.

By the way, although I'm not sure about the correlation, Ubuntu shows this crash report whenever I catkin_make my workspace. --> http://pastebin.com/gCYFXBDY

Groovy, Precise
python_qt_binding from debian
rqt & qt_gui_core from source, built with catkin.

**Comment by 130s** [comment]
Sorry I wrote Fuerte but apparently it's tested under Groovy (original post is now corrected).

**Comment by ablasdel** [comment]
are you sure this isn't issue #16?

It sounds very similar.

**Comment by 130s** [comment]
Although not sure about correlation with Issue #16, this stopped happening with qt_gui_core 0.2.7 fetched (from building server).
