### ISSUE TITLE
(rqt_robot_monitor) timeline on popup window doesn't show retrospect values.

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#45]
Happens with rqt 919884dd133ce40688c1206a01653161d8eff0cc

Expected behavior:
When user clicks on any device trees, popup window appears to show detail of the device status, which gets updated upon the arrival of new diagnostic msg. There is also timeline on the popup where user is able to scroll to  go back see previous status.

Error phenomenon: 
Scrolling on timeline on popup doesn't change the device status shown.

**Comment by ablasdel** [comment]
Could you explain this bug more completely?

**Comment by 130s** [comment]
Sorry I added description on the original post.

**Comment by zklapow** [comment]
this isn't really a bug per-say more of an "I never implemented this feature" because of time.

**Comment by ablasdel** [comment]
I agree I'm marking this as enhancement instead of bug. It would still be nice to have.

**Comment by 130s** [comment]
@zklapow Because I'm talking about the current version that I'm working on, it's not your fault ;)

@ablasdel and I agreed it still counts as a bug. Users expect the feature I described above, when they see the popup window.

**Comment by 130s** [comment]
Fixed in b54ab4060f341d6e616475e8415b81c8a8b7f98f
