### ISSUE TITLE
No rospy logger shown on rqt_logger_levels

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#5]
Phenom shared with Aaron.

Considering rqt_logger_levels is a direct port from rxloggerlevel, which currently doesn't handle logs from rospy (see Ken's answer http://goo.gl/MHpc9 made in 2011), solution requires to modify rospy's logging system (unless making huge workaround within this plugin, which I suspect realistic).

**Comment by 130s** [comment]
This feature req is probably dependent on https://github.com/ros/ros_comm/issues/14

**Comment by ablasdel** [comment]
@dirk-thomas The rospy branch was merged correct? Are we leaving this open because it was not backported to Fuerte? or should this be closed?

That said even if it should be open maybe this issue belongs on ros/ros_comm if it will be open for a significant period of time.

**Comment by dirk-thomas** [comment]
The patch to rospy has been committed to fuerte and groovy (but not yet released. As soon as we have verifies that rqt_logger_levels now works as expected we can close this.

**Comment by ablasdel** [comment]
Ok I will ask @130s to see if he can verify this is solved.

**Comment by 130s** [comment]
On Groovy this is tested and rospy logger showed up on rqt_logger_levels (Fuerte not tested). Changing to Levels = Debug on Loggers = rosout prints rospy.logdebug (tested with rqt_robot_monitor).
