### ISSUE TITLE
rqt_robot_monitor) Popup windows generated from either warn/error trees disappear when their status change

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#50]
== Severity ==
Minor, but could become major.

== Observed effect to the system ==
So far I haven't observed any major/minor effect on the entire rqt_gui because of this. 

== How to reproduce ==
With rqt b54ab4060f341d6e616475e8415b81c8a8b7f98f, Precise
Step-1. Spend sometime watching rqt_robot_monitor/rqt_pr2_dashboard, know in advance which device status often changes b/w ok <--> warning/error.
Step-2. When the device appeared in either warn/error tree, double-click it so that a popup appears.
Step-3. Leave it for awhile to wait the status changes/disappears from the tree where it was in Step-2.

== Cause of the phenomenon ==
Each of 3 trees (all devices, warning, error) uses different instance of StatusItem class, that hold an instance of the associated popup window. In particular, warn & error deletes StatusItem instance once the status changes.

== Possible workaround/solution ==
Modify RobotMonitorWidget._update_flat_tree method to use same StatusItem instance with the ones that all-device tree uses.

**Comment by ablasdel** [comment]
This is due to the popups you being a child of the items in the treeview.

If you want them to be persistent you will need to create them in a callback.

This might be a problem due to the inability to look at error messages unless robot_monitor is paused.

A quick fix might be to pause the robot monitor when you open an error or warning box.

**Comment by 130s** [comment]
> This is due to the popups you being a child of the items in the treeview.

Partly true partly not. As I mentioned in my org. post, there's still a way to achieve what I want with the current tactics.

> This might be a problem due to the inability to look at error messages unless robot_monitor is paused.
> A quick fix might be to pause the robot monitor when you open an error or warning box.

Agreed that it is a quick workaround but that would change the system behavior, and I feel it's a huge change for the users. Let me discuss further with you later on.

**Comment by 130s** [comment]
Migrated to https://github.com/ros-visualization/rqt_robot_plugins/issues/3
