### ISSUE TITLE
rqt_math: plugin to perform math expressions on topics/fields

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#51]
For example you have a few numeric topics you want to monitor but would prefer to monitor the sum of them. 

This becomes even more useful if it allows arbitrary expressions with topics as variables.

**Comment by dirk-thomas** [comment]
The mathematical operation should probably be performed by a separate node and not within rqt_topic.

**Comment by ablasdel** [comment]
Do you mean a separate plugin for doing combinations?
Some basic Topic analysis seems like it would fit in quite nicely in the topic introspection plugin

**Comment by dirk-thomas** [comment]
Yeah, a separate plugin should have incoming topics/fields, perform the arithmetic and than output the results on new topics. Because that logic is orthogonal to rqt_topic - it would apply to rqt_plot etc. as well.

**Comment by ablasdel** [comment]
I like that idea. A plugin that takes in any number of topics and combines
them by equation.
If we want to get ambitious it could even publish a result.

**Comment by dirk-thomas** [comment]
Moved: ros-visualization/rqt_common_plugins#88
