### ISSUE TITLE
rqt_logger_level: Save and restore logger levels & multi process level setting

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#52]
Redesign the plugin to allow block selecting so you can set the logger level of multiple processes at the same time.

implement a save/load from a file OR implement the rqt save/restore functionality.

**Comment by dirk-thomas** [comment]
rqt save/restore functionality is not feasible here since the remote side has a state which you don't want to override when opening the plugin.
Block editing and save/load from a file would be great.

**Comment by ablasdel** [comment]
I agree this needs to be a manual save to a file not through the
save/restore functionality.
