### ISSUE TITLE
missing rqt_console script in fuerte

### ISSUE THREAD

**Issue by tkruse** [ros-visualization/rqt#54]
rqt in fuerte misses a script named rqt_console, hence the command 

```
$ rosrun rqt_console rqt_console
```

fails. This breaks tutorials like:
http://www.ros.org/wiki/ROS/Tutorials/UsingRqtconsoleRoslaunch

See:
http://answers.ros.org/question/50238/rqt_console-and-rqt_logger_level/?answer=50260#post-id-50260
I added note to tutorial in the meantime.

BTW: Also in groovy, rqt_console has empty bin and lib folders, which looks ugly.

**Comment by tkruse** [comment]
Same for rqt_logger_level, and best check other plugins as well.

Not sure whether electric is affected as well.

**Comment by ablasdel** [comment]
It sounds like the 1.5 release only got released for groovy and fuerte
is still 1.4.

Can you check your deb version?

**Comment by tkruse** [comment]
$ dpkg -s ros-fuerte-rqt
...
Version: 0.1.2-s1352880492~precise

**Comment by ablasdel** [comment]
Well there's your problem. I'll work on getting 1.5 released against fuerte.

Also Rqt doesn't support Electric.

**Comment by ablasdel** [comment]
This has been fixed now that Fuerte version 1.6 is released and in debians.
