### ISSUE TITLE
Needs docstring style policy

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#55]
I think rqt better specifies docstring format policy. Some info:
- PEP257[1] & 258 leave up the detailed format to each project
- Most of the rqt plugins so far look like using Sphinx format [2].

Maybe PEP 258 + Sphinx is rqt default? If so, then how strict/loose it should be?

[1] http://goo.gl/FZjJj
[2] http://sphinx-doc.org/markup/desc.html, 
     http://packages.python.org/an_example_pypi_project/sphinx.html#full-code-example

**Comment by DorianScholz** [comment]
I second this. 
Sphinx seems to be the way to go.

**Comment by 130s** [comment]
I propose that in addition to what's discussed above, allow using @ for attributing. For example:

```
@param argfoo: this is argfoo
```

is equal to:

```
:param argfoo: this is argfoo
```

I'm suggesting because `pydev` seems to be supporting @. 

I'm closing this assuming no objection but feel free to reopen.

**Comment by dirk-thomas** [comment]
Do both syntax variations work with all the used tools?

**Comment by 130s** [comment]
Reopened since we're not sure about side effect of the change I proposed.

**Comment by dirk-thomas** [comment]
I will close this ticket in rqt since it is not the responsibility of rqt to define the recommendation for documenting Python code in ROS. Please feel free to continue the discussion on one of the mailing lists to achieve a state which can than be documented on the Wiki.
