### ISSUE TITLE
rqt plugins for roslaunch

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#57]
Interface to easily edit/save/launch robot launch files. 

Features TBD.

**Comment by honorh** [comment]
Hi,

Our three biggest requests are all for a GUI that you could use during runtime as a supplement or possibly even a replacement to the rosout GUI:

1) A GUI to display the start/stop/crashed state of each process, along with standard output, standard error, memory and cpu usage.  The rosout GUI only does stdout/stderr.  The worst part of this is not being able to tell without looking at the terminal in which you launched the process whether a process has seg faulted, but cpu and memory statistics would also be very helpful.

2) The ability to restart individual processes from the GUI even if they were launched from the same file.

3) A tie-in with rosbag that lets you do launch file analysis:  Record some data, then playback the log file and use the GUI to watch process stdout/stderr, memory/cpu usage, processes starting/stopping, system load, etc.

If you want a more specific example, an interface we like for doing this is bot-procman from libbot.  Several people here use it with ROS but it requires some work.  Having a native roslaunch GUI would be great.
http://code.google.com/p/libbot/

As a secondary concern, we would also like an easy way to generate a launch file dependency graph in both directions.  We would like to be able to see what files a launch file depends on all the way down (so if a file includes a file that should be in the graph) and also, if possible, what launch files include a specific launch file.  There may already be a way to do this - I thought I saw someone demo it - but I couldn't find it when I looked.

An editing GUI with a nice drag-and-drop interface for creating a launch file would be cool, but much less important to us than any of the rest.

Thanks!
-Jenny

**Comment by 130s** [comment]
@honorh these seem all good ones. Just commenting back - I felt that we might be able to split features into the one that handles node's process status and another one that provides launch-related functions (and of course we can integrate those features into a single GUI). 
Also your idea (1) sounds nice. I wonder how it's feasible though. It might require all the nodes that you want to observe to implement something that returns process status to ROS?

**Comment by 130s** [comment]
@honorh It's appreciated if you could find one that shows launch dependency.
For start/stoping nodes, I found rxlaunch http://goo.gl/vodJO which could be a good basis for rqt_launch.

**Comment by honorh** [comment]
Hi Isaac,

I'm not completely sure what you're asking.  rxlaunch looks like a good
place to start, though, I agree.

-Jenny

**Comment by 130s** [comment]
Jenny, I am wondering if you could remember a demo you said you saw. Thanks.

> As a secondary concern, we would also like an easy way to generate a launch file dependency graph in both directions. We would like to be able to see what files a launch file depends on all the way down (so if a file includes a file that should be in the graph) and also, if possible, what launch files include a specific launch file. There may already be a way to do this - I thought I saw someone demo it - but I couldn't find it when I looked.

**Comment by honorh** [comment]
I can't find the demo, but I would basically like a graphic of the output of roslaunch dep.  And, if possible, a way to go backwards - to see what files depend on the current launch file.

**Comment by 130s** [comment]
Just sharing that what's discussed so far is also noted in a ticket opened 4 yrs ago (and labeled as wontfix w/o reason mentioned).
https://code.ros.org/trac/ros/ticket/974

**Comment by 130s** [comment]
Just summarizing the functional requirements into a usecase diagram. Opinions still welcomed.
https://docs.google.com/drawings/d/12IDxbt6f9gNv0_Sn6wqKgU5sL5fQHraiHKzX96tJ2cI/edit?usp=sharing

**Comment by honorh** [comment]
Hi,

In UC.4.2, would it be possible to also monitor stdout and stderr?  People still write to those directly fairly frequently instead of using the ROS logging system.

Thanks,
Jenny

**Comment by 130s** [comment]
> People still write to those directly fairly frequently instead of using the ROS logging system.

We might want to open another ticket for that.

Joking aside, I'll think about it, but my guts says it might be hard to fit printouts of many lines into this GUI (display region will be occupied with many info). Also ideally we should not be too permissible for non-standard programming habit IMHO.

**Comment by dirk-thomas** [comment]
Please consider creating multiple smaller rqt plugins rather than one-plugin-addresses-all. The originally proposed 3) goes far beyond what a rqt_launch plugin should be responsible for.

**Comment by 130s** [comment]
Without having said so clearly (my bad), I've been using this thread to collect feature requests for rqt plugin(s) regarding `roslaunch`. So `roslaunch` users can still feel free to post what they want (I also changed the title of the thread accordingly). I will manage the balance based on modularity, reusability (eg. split into multiple plugins as @dirk-thomas mentioned).

**Comment by 130s** [comment]
1st release of `rqt_launch` is pushed to buildfarm, so hopefully you'll be able to download its debian pkg in a few days. Many features are yet missing.

Mainly @honorh, about .launch files hierarchy, current version shows all nodes regardless in which .launch files they are called. I thought in some cases this is enough but please tell me once you get to see how it works and how you think.

**Comment by 130s** [comment]
Closing this feature discussion, since development is going on and 1st release is being built. Please file tickets for further enhancement and issue report on designated issue tracker. See [wiki](http://ros.org/wiki/rqt_launch) for more info.
