### ISSUE TITLE
rqt_logger_levels: a node is missing

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#60]
With PR2, I just happened to find a node `/localization_saver`  is not shown on "Nodes" pane on rqt_logger_levels. Not sure if this happens with any other nodes.

Because `rxloggerlevel` doesn't show this node either, it's also possible that this might be an issue in ROS level.

By the way, `rqt_console` shows the output from  `/localization_saver` node. No idea if they are correlated or not.

rqt 46ee6dd15347ca8a236ff4ff77be7786bb3ec024
ros-groovy-rosservice/precise uptodate 1.9.34-0precise-20121207-0912-+0000
ros-groovy-rosnode/precise uptodate 1.9.34-0precise-20121207-0844-+0000

**Comment by ablasdel** [comment]
Is it possible this is the same bug as #65 ?
We recently moved it over from trac

**Comment by 130s** [comment]
I looked at #65. The reported phenomenons are different (there they talk about "Logger" pane whereas this issue is about "Node" pane). 

However I can't determine that they are not rooted in the same cause. Especially I can't reproduce this problem on `PR2` (prj at Willow), failing to find `/localization_saver` node both by `rqt_logger_level` and by `rosnode`. Maybe I need to run some `navigation` nodes? Anyway I'll keep watching if this issue occurs.

**Comment by ablasdel** [comment]
I have closed #65 as not reproducible for now. If you can't figure out how to make this one happen please do the same with this bug. 

Even if we reproduced it the bug would most likely be in rosgraph since all rqt_logger_level does is display what rosgraph gives it.
