### ISSUE TITLE
the ros-groovy-rqt-core package doesn't seem to depend on ros-groovy-ros or ros-groovy-ros-comm

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#64]
This seems important

**Comment by ablasdel** [comment]
When installing just the ros-groovy-rqt-core package on a clean system it doesn't create a /opt/ros/groovy/setup.bash etc...

this makes it impossible to run any rqt plugins.

**Comment by dirk-thomas** [comment]
This is true for every package. If you want the setup files to be present you must have a run_depend on catkin.
