### ISSUE TITLE
rqt) TypeError: main() got an unexpected keyword argument 'plugin_argument_provider'

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#66]
I see this on 2 different `Quantal` machines.

```
isaito@btt:~/ROS/groovy_quantal/catkin_ws/src/rqt/rqt$ roscd rqt_gui
isaito@btt:~/ROS/groovy_quantal/catkin_ws/src/rqt/rqt_gui$ rqt &
[1] 32756
isaito@btt:~/ROS/groovy_quantal/catkin_ws/src/rqt/rqt_gui$ Traceback (most recent call last):
  File "~/ROS/groovy_quantal/catkin_ws/devel/bin/rqt", line 5, in <module>
    exec(fh.read())
  File "<string>", line 16, in <module>
  File "~/ROS/groovy_quantal/catkin_ws/src/rqt/rqt_gui/src/rqt_gui/main.py", line 57, in main
    return super(Main, self).main(argv, standalone=standalone, plugin_argument_provider=plugin_argument_provider)
TypeError: main() got an unexpected keyword argument 'plugin_argument_provider'

[1]+  Exit 1                  rqt
```

rqt is from source 4f232265f7e571743eaeef7a07060ab08fe23208

```
$ dpkg -p ros-groovy-qt-gui-core 
0.2.9-0quantal-20121230-1135-+0000
```

**Comment by dirk-thomas** [comment]
If you are working with the latest version from source please take a look to the commit log first before filling new issues.

The error message indicates that the called parent constructor does not have that argument. This is a recent change and it requires you to have also the latest version of qt_gui_core (until that is available as a Debian package also from source).

**Comment by 130s** [comment]
I see. With `qt_gui_core` built from source, I don't see this happens.

Now I understand that we need to use `qt_gui_core` from source too if we work on `rqt`\* from source.

For the reference purpose I think the change mentioned above is probably this https://github.com/ros-visualization/qt_gui_core/commit/33340b32abd5b16b3dd708aef9c16acf740d536a

**Comment by dlaz** [comment]
I'm seeing this with the latest version from the debs on quantal. 

```
$ dpkg -s ros-groovy-qt-gui-core
Version: 0.2.12-0quantal-20130126-0207-+0000
```

**Comment by dirk-thomas** [comment]
You are likely not using the latest packages. Please dist-upgrade your system and recheck that you have:
ros-groovy-qt-gui 0.2.12-0quantal-20130125-2007-+0000
ros-groovy-rqt-gui 0.2.8-0quantal-20130125-2010-+0000

**Comment by dlaz** [comment]
That did it. Odd because this was on a fresh install of ubuntu (from today), so I don't understand why it would have pulled old packages.
