### ISSUE TITLE
inconsistent behavior on rqt_gui start without running roscore  (ros-pkg ticket #5562)

### ISSUE THREAD

**Issue by tfoote** [ros-visualization/rqt#67]
current behavior:
- roscpp plugins are available
- rospy plugins are disabled
  - rospy plugins that were loaded in the previous session are restored anyways, leading to init_node waiting for roscore
  - some plugins don't even need roscore (i.e. rqt_dep), but init_node is always called, when loading a plugin

desired behavior:
- same treatment for rospy and roscpp based plugins

option 1)
- plugins should specify in their plugin.xml whether they need roscore or not

option 2)
- rqt_gui should just launch a new roscore if none is running (nice for new users, maybe not desirable for advanced users)

trac data:
- Owner: **dthomas**
- Reporter: **dorianscholz**
- Reported at: **Tue Sep 18 04:34:55 2012**
- URL: https://code.ros.org/trac/ros-pkg/ticket/5562

**Comment by dirk-thomas** [comment]
The exact same treatment is not possible as roscpp and rospy expose not the same functionality which would be necessary.

**Comment by dirk-thomas** [comment]
This is addressed by #85
