### ISSUE TITLE
rqt scripts installed to global PATH

### ISSUE THREAD

**Issue by tkruse** [ros-visualization/rqt#68]
I assume this was done in the migration to Groovy, but most or all of those scripts should not be installed to the PATH:
['rqt', 'qt_gui_app', 'rqt_bag', 'rqt_console', 'rqt_graph', 'rqt_logger_level', 'rqt_plot', 'rqt_reconfigure']

**Comment by dirk-thomas** [comment]
rqt and the core tools previous available as rx\* are intentionally still on the path. qt_gui_app has been moved to package specific bin folder.

**Comment by 130s** [comment]
Technically `reconfigure` GUI wasn't in `rx` suite but in `dynamic_reconfigure`. I'm ok with either to delete from PATH or to keep it as it is.

**Comment by dirk-thomas** [comment]
@130s: can you check if it was on the path before and if not remove the script from setup.py?

**Comment by 130s** [comment]
It was added in 24c16b05cf5792cdb417afd896a274486cf69775 by me without considering `rx` orientation.
Should be removed from PATH via https://github.com/ros-visualization/rqt_common_plugins/commit/231169310aef8bed6b6faabc6ff4862f4d83c8f5#rqt_reconfigure/setup.py
