### ISSUE TITLE
rqt_gui) Move config file location to ~/.ros

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#69]
Since it looks like config file's default location is ~/.ros in ROS world ([related thread](http://answers.ros.org/question/53861/rulepractice-for-the-location-of-storing-config-files/)), `rqt_gui` might better use it too unless there's specific reason.

**Comment by 130s** [comment]
Idea of @dirk-thomas is this is 'wontfix'.

Content of config file is used in one of its dependency `qt_gui_core` metapackage, which will be ROS agnostic (currently it depends on ROS but eventually will become so, once [REP136](https://github.com/ros-infrastructure/rep/blob/9701098708b094005878be5a7ef29e4f5ebc3ff9/rep-0136.rst) finalizes). 

So it makes sense to use normal `Ubuntu` way, which is to create `ros.org` in `~/.config` directory what `rqt_gui` currently does.

**Comment by dirk-thomas** [comment]
We can move the config in the future for the ROS specific part of rqt, but we have to make sure to make it transform existing configurations from the current location.

**Comment by dirk-thomas** [comment]
rqt uses the Qt mechanism to store the configuration in the system default location. At provides an option to clear the configuration. Furthermore the config file is not really human readable/editable with all its serialized state information. Therefore I don't think it makes a lot of sense to move it to the .ros folder.

Until there is some strong interest and reason to migrate to a ROS specific location I will close this as "wontfix".
