### ISSUE TITLE
rqt_reconfigure exec not present in 0.2.11

### ISSUE THREAD

**Issue by vrabaud** [ros-visualization/rqt#70]
It seems it's related to #68 : 
rosrun rqt_reconfigure rqt_reconfigure
does nto work anymore
(the script is not copied over, the CMake install call seemed fine to me, it was nto installing to the global PATH, not sure why it was removed).

**Comment by ablasdel** [comment]
This is actually a bug that should live on rqt_common_plugins. 

The issue is the script is not installed properly: fixed here https://github.com/ros-visualization/rqt_common_plugins/commit/0cf9d223e6cf2a791e64144f8a1fbb7d3f714e92

**Comment by vrabaud** [comment]
True, it's an rt_common bug but it was caused by the generic bug #68 in rqt.
