### ISSUE TITLE
rqt version of create_pkg command

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#71]
Following files are currently developers' responsibility in addition to writing codes, and it's still cumbersome to me after creating pkgs 20+ times:
- Modify package.xml
- make plugin.xml
- Modify CMakeLists.txt
- (py) Modify setup.py
- (py) Modify scripts folder

If this is a good idea I'll give it a try.

**Comment by dirk-thomas** [comment]
The milestone is set to "untargeted" since nobody plans to work on this. If someone is interested in this feature a pull request is always welcome.

**Comment by dirk-thomas** [comment]
I will close this since it is not likely that it will happen. Any contribution to implement this feature would be highly welcome.
