### ISSUE TITLE
panel dragging cannot acheive certain layouts

### ISSUE THREAD

**Issue by acornacorn** [ros-visualization/rqt#72]
To reproduce:
run rqt
open any 3 plugins (e.g. console, launch, and ROS Graph)
typical arrangement is all 3 side by side.
Drag one of the panels and try to get it to take up the entire bottom of the window (with the other 2 side by side on top).  

Expected: should be able to make one panel take the entire width of the window with the other 2 side by side on top (or bottom)

Actual: seems impossible to achieve this.

**Comment by dirk-thomas** [comment]
It is absolutely possible: ![rqt-3-plugins](https://f.cloud.github.com/assets/1335366/292917/9f142068-9338-11e2-85eb-da5906ea8747.png)

This is totaly up to Qt - rqt does nothing special - but yes, it is not straight forward to achieve.
You first undock one plugin, than stack the other two vertically above each other and that redock the first plugin beside the top one.
