### ISSUE TITLE
(rqt_gui) panel min size is too large

### ISSUE THREAD

**Issue by acornacorn** [ros-visualization/rqt#73]
(feature request)

Many rqt plugins have a minimum width that is pretty large.  With even a modest number of plugins side by side this makes it impossible to shrink the rqt window much.  It would be useful if there was one or more of:
- an option to allow forcing panels to shrink smaller than their min size
- the ability to minimize a panel so it can easily be popped open again when needed (minimizing it would mean it only takes a few pixels horizontally or vertically)
- the ability to add a tabbed panel which shows one of several subpanels (so one of several can be viewed at a time)

**Comment by dirk-thomas** [comment]
- the definition of a minimum size is that you can not size it smaller, you could fill issues for individual plugins to decrease the size of their layout if feasible
- you can already make the plugins stack and get a tabbed panel, try to move a plugin over the middle of another plugin and watch the rubber band where it will be dropped.
- I have filled a feature request for minimizing plugins: ros-visualization/qt_gui_core#13

Closing this issue.
