### ISSUE TITLE
Docstring process needs documented for python in rqt

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt#74]
This is `ROS` wide and is not necessarily `rqt` only, but I want to start working on `rqt` and once successful then propagate to ROS.

Writing and publishing `Docstring` process needs documented. Specifically:
- [ ] Which format docstring should be written (discussed in Issue #55)
- [ ] Necessary steps to be made if any in order to generate API doc that's nice enough 
  - [Example in rospy](http://ros.org/doc/groovy/api/rospy/html/rospy.impl.init-module.html) -- argument is indented and its type is parenthesised.

Although less priority, what's even nicer:
- [ ] How to enable code auto completion in IDE (`PyDev`. What else?)

**Comment by 130s** [comment]
As part of the best-practice, always defining `rtype` seems to be beneficial ([ref.](http://sebthom.de/140-leveraging-pydevs-auto-completion-indirectly-created-objects/)) for auto-completion. This works quite well on `PyDev` on `Eclipse`.

**Comment by dirk-thomas** [comment]
The reference states:
"But PyDev could for example honor the @return / @rtype PyDoc annotations (which you can add to the findBook’s method declaration) but currently it just does not."

Have you tried it with PyDev and it worked for you? If yes, with which version?

**Comment by 130s** [comment]
[With PyDev 2.8.1 type inference from DocString is introduced](http://pydev.blogspot.com.au/2013/07/pydev-280-released.html). Works great.

**Comment by dirk-thomas** [comment]
I will close this ticket in rqt since it is not the responsibility of rqt to define the recommendation for documenting Python code in ROS. Please feel free to continue the discussion on one of the mailing lists to achieve a state which can than be documented on the Wiki.

**Comment by 130s** [comment]
Agreed to close, so do I with #55 too.
