### ISSUE TITLE
rqt on MacOSX fails to start [ImportError?]

### ISSUE THREAD

**Issue by tsirif** [ros-visualization/rqt#77]
I followed Homebrew source installation of Groovy on MacOS 10.7.5 and when i'm trying to run rqt i get the following error:

```
ImportError: numpy.core.multiarray failed to import
'import sitecustomize' failed; use -v for traceback
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/rosdep2/__init__.py", line 34, in <module>
    from __future__ import print_function
ImportError: No module named __future__
[rospack] Error: could not find python module 'rosdep2.rospack'. is rosdep up-to-date (at least 0.10.4)?
[librospack]: error while executing command
terminate called throwing an exceptionAbort trap: 6
```

What is wrong? Can you help me?

**Comment by 130s** [comment]
This seems like a known issue discussed [here](http://answers.ros.org/question/56477/python-conflicts-with-homebrew-based-install-on-osx/).

Also, please consider asking questions on the [same web site](answers.ros.org). Only when you determine something as bug/enhancement, please open ticket here (like you did). Reviewing [ROS' support policy](http://www.ros.org/wiki/Support) will be hopefully helpful.

Looks like the discussion hasn't seen a solution, but I suggest to keep developing the same thread is the best way to tackle, and don't hesitate to eopen this issue once the issue gets settled as bug/needs enhancement.
