### ISSUE TITLE
Problems installing ros-groovy-rqt from apt package manager

### ISSUE THREAD

**Issue by osandoval** [ros-visualization/rqt#78]
I'm trying to install ros-groovy-rqt from the default ros repository, on a computer with Ubuntu 12.04 (precise) and amd64 architecture. If, as root, I use the command:

```
# apt-get install ros-groovy-rqt
```

I get the following error:

```
Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/r/ros-groovy-rqt/ros-groovy-rqt_0.2.8-0precise-20130402-2353-+0000_amd64.deb  404  Not Found
```

I just search the .deb file in http://packages.ros.org/ros/ubuntu/pool/main/r/ros-groovy-rqt/ and I found that the clossest package is:

```
ros-groovy-rqt_0.2.8-0precise-20130419-1953-+0000_amd64.deb
```

Is not hard to download and install a package manually, but I'm sure that this kind of problems could reduce the interest of some ROS users.

**Comment by dirk-thomas** [comment]
This is very likely due to the fact that an updated package (newer timestamp) has been released after you called `sudo apt-get update` last time. Try running that command again and afterwards the installation should work fine - if not, please comment again and I might reopen the issue.

**Comment by osandoval** [comment]
You were right, timestamps were unupdated. Thanks.
