### ISSUE TITLE
Allow perspective in rqt_gui window to be locked

### ISSUE THREAD

**Issue by shaun-edwards** [ros-visualization/rqt#79]
The current perspectives are very useful from a power user point of view but they could be confusing from a simple user point of view.  It would be nice if there were a way to lock a perspective so that it automatically loaded with rqt_gui and could not be changed by the user.  Ideally this would be done from the command line, config file, etc... so that an application could be loaded and configured without any knowledge on the end users side.

**Comment by dirk-thomas** [comment]
rqt currently has the options:

```
-l, --lock-perspective
lock the GUI to the used perspective (hide menu bar and close buttons of plugins)
(This still allows to move/resize dockwidgets, but not open/close)

--perspective-file PERSPECTIVE_FILE
start with a perspective loaded from a file
```

Is that what you want or do you have anything else in mind?

**Comment by shaun-edwards** [comment]
I tried the -l and -p options under fuerte and observed the following behavior.

-p loaded the desired perspective as expected

-l disabled the menu and the "close" icon plugins.  The "close" icon on the Container was not disabled.  This is probably a bug, but I was not able to verify it in groovy.

Using the -l and -p options appears to do most of what is requested, but they still allow moving and resizing of widgets.  Even an experienced user (such as myself) has problems getting a proper layout.  It would be nice if -l or some other option disabled the move/resize capability as well.

**Comment by dirk-thomas** [comment]
It ticketed the two parts separately: ros-visualization/qt_gui_core#20 ros-visualization/qt_gui_core#21.
Therefore closing this meta issue.
