### ISSUE TITLE
rqt_graph) Bring back node information

### ISSUE THREAD

**Issue by dpsolomon** [ros-visualization/rqt#80]
Part of what made rxgraph so useful was the node information (pubs, subs, services, and active connections) that was readily available all in one spot. Yes, I know the information is still available via rosnode, but a very useful enhancement to rqt_graph would be to bring back the node information in the sidebar.

**Comment by ablasdel** [comment]
I agree this would be a great enhancement. I don't think the creator is actively developing this anymore but I will look around for someone interested. If you know anyone have them contact me.

**Comment by dirk-thomas** [comment]
Moved: ros-visualization/rqt_common_plugins#87
