### ISSUE TITLE
Strange rendering behavior on OSX

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt#83]
Initially reported on rqt_bag here: https://github.com/ros-visualization/rqt_common_plugins/issues/68

It seems that the qt Version of OSX has some rendering irregularities.

**Comment by ablasdel** [comment]
I couldn't find a similar bug so I filed a bug here: https://bugreports.qt-project.org/browse/PYSIDE-183
If it can be verified in pyqt as well I will move the bug.

@wjwwood Not sure if anyone will care though.

**Comment by dirk-thomas** [comment]
Before filling bugs upstream you should make sure that it is really a PySide error. Have you ran it with both PyQt and PySide and verified that it only happens for PySide but not for PyQt? Do you have a simple PySide example (without using ROS, rqt, etc.) which demonstrates the rendering issue?

**Comment by ablasdel** [comment]
I do not and william just verified that it is not a pyside. happens in pyqt also.

**Comment by dirk-thomas** [comment]
As far as I know fixing the rqt_bag ui file has solved the issue. @ablasdel Are there any other cases left?

**Comment by ablasdel** [comment]
I have not personally seen the issues but @wjwwood has informed me that a number of the other tools are similarly unusable due to similar issues.

**Comment by dirk-thomas** [comment]
The default icon size is different on OS X. Therefore the ui files must always contain specific values for iconSize if the push buttons get icons from within the code. Even if the default size (16x16px) is correct is must be set explicitly. Done in ros-visualization/qt_gui_core@edc2c9d4c99d62afc38f2f2a2f390ff7274dd15c

**Comment by dirk-thomas** [comment]
The minimize button was empty since the underscore character is just a bit below the 16x16px rect specified. Sophisticated patch for this in ros-visualization/qt_gui_core@62e77781bb3f0e647ecae97a205e065fbd701d2c

**Comment by dirk-thomas** [comment]
Generally when using icons from the theme it should be checked if the theme really provides them (e.g. window-close is not available on OS X). Added checks for each icon in ros-visualization/qt_gui_core@f2e88cdcd337357db12c8ad02371e9800430b6db

**Comment by dirk-thomas** [comment]
These were all the OS X specific rendering issues which are generic to qt_gui_core and rqt. For further issues please fill tickets against the individual plugins or provide simple pull requests for them to fix similar issues like the ones above.
