### ISSUE TITLE
rqt standalone plugins have superfluous buttons

### ISSUE THREAD

**Issue by tkruse** [ros-visualization/rqt#84]
When I start rqt tools stand_alone, they still have the qt Functions like undocking, docking enable button, minimization, toggle floating, and an inner Window title (e.g. for rqt_console, the title "Console", adding nothing to what we know unless we undock).

Those functions are not useful in the standalone case as far as I can see, and worse when pressed accidentally, they are an annoying distraction. The only useful buttons are help and settings, but taking away the screen space of the bar just for 2 buttons is also wasteful.

**Comment by dirk-thomas** [comment]
This can not be changed.

rqt is designed as a framework and each plugin is able to contribute multiple widgets. So it is not feasible to assume  that a plugin only consists of a single dock widget. Therefore for standalone plugins the main window surrounding the dock widget(s) can not be removed.

**Comment by tkruse** [comment]
I am mildly curious: then how come rqt_pr2_dashboard comes without these buttons ?

**Comment by dirk-thomas** [comment]
rqt_pr2_dashboard has the same buttons for every dock widget. What you see at the start of the dashboard is a toolbar which naturally does not have a title bar.

**Comment by tkruse** [comment]
I see.

Assuming the current dockable-widget design of stand-alone rqt tools was
not acceptable to the ROS community, what would be the best approach to
achieve stand-alone tools (for rosbag, console, dashboard, etc) without
superfluous buttons using simething rqt-like?

Would it be easier to change rqt to offer a richer API, or to change the
respective stand-alone tools to be more independent of the rqt design?

**Comment by dirk-thomas** [comment]
I don't see how this would fit into the current rqt design. The title bar contains functionality (e.g. plugin settings) which are necessary to keep.

If you think that there is need for that and know how to address it please feel free to provide a complete prototype / patch to discuss such an enhancement on the rqt SIG.
