### ISSUE TITLE
Launch file dependency grapher

### ISSUE THREAD

**Issue by b-adkins** [ros-visualization/rqt#86]
Files:
[launch_include_graph.sh](https://gist.github.com/b-adkins/6368918#file-launch_include_graph-sh)
[example.dot](https://gist.github.com/b-adkins/6368918#file-example-dot)
[example.pdf](https://gist.github.com/b-adkins/6368918#file-example-pdf)

I wrote a quick dependency grapher. It uses BASH, ros command line tools, and regular expressions to parse launch file includes into DOT node edges. It's not portable (like e.g. Python), but I hope it can be a useful starting point. It should be easy to port. If there were to be an "export graph to file" option, the DOT file generation code could be used for that.

While the advanced tree viewer in the GUI is under development, perhaps a simpler tool that generates PDFs could be released to benefit the community?

**Comment by jbohren** [comment]
Cool! Yeah, even just adding it to ros_comm as a command-line utility to start would be good. Maybe you could create a pull request in the ros_comm package with the contributions.

**Comment by b-adkins** [comment]
Okay. I just have to find a place to put it then. My one concern is that it's a shell script, not portable Python.

Also, what's a good name for this utility? 
- roslaunch/dep_graph
- roslaunch/gen_graph
- roslaunch/inc_graph

Or maybe I could use the name of the advanced graphing tool, which once it's released, could call this tool with a certain flag?

**Comment by dirk-thomas** [comment]
I will close the ticket since this specific plugin is not part of this repo.

If there has been any progress on this please add the plugin to the list of available ones / in developement in the wiki: http://wiki.ros.org/rqt/Plugins

**Comment by charles-maheu** [comment]
In case someone else finds this issue while looking for a graph tool specific to launch files, I've updated and improved a bit the script. I've also added nodes that are started by launch files in gray to better visualise complicated projects.
Here's the script :
[launch_include_graph.sh](https://github.com/ros-visualization/rqt/files/7287683/launch_include_graph.txt)

Here's an example of the result :
[wheelchair_common_gui.pdf](https://github.com/ros-visualization/rqt/files/7287697/wheelchair_common_gui.pdf)
