### ISSUE TITLE
rqt Launch plugin ignores machine attribute

### ISSUE THREAD

**Issue by jgdo** [ros-visualization/rqt#93]
I have some launch files where nodes are supposed to be started on a certain machine using the "machine" attribute. Using roslaunch works fine, but when starting the launch file using the rqt launch plugin, the machine attribute seems to be ignored and the node starts on the local computer.

Is there a way to fix this with some setting or something?

**Comment by dirk-thomas** [comment]
Moved to ros-visualization/rqt_common_plugins#203
