### ISSUE TITLE
rqt main window keyboard shortcuts [feature request]

### ISSUE THREAD

**Issue by davetcoleman** [ros-visualization/rqt#94]
It would be really nice to have shortcuts to open things like the plugin menu (Alt-P). From past experience (non-python) this is usually accomplished by changing the menu string slightly

**Comment by DorianScholz** [comment]
Thanks for the feature request. I don't know why we didn't have that already...
I implemented it in https://github.com/ros-visualization/qt_gui_core/commit/ea48b623306c531061edc23aa7b6bcf62f885775
