### ISSUE TITLE
can't see the service call plugin and other none basic plugin

### ISSUE THREAD

**Issue by robotpilot** [ros-visualization/rqt#98]
Dear All,

My develop environment is below,
install the ros-indigo-desktop-full and ros-indigo-rqt-\* in Ubuntu 14.04 LTS 64bit.

Today, I launch rqt and then I search the other plugin like service call. 
However, I can't see the service call plugin and other none basic plugin (Plugins menu).

When I used the ros indigo beta version, it is working. 
But, today I re-install the ros-indigo-desktop-full, It don't working.

I have experience this issue in different computers.

In advance thank you for your help.

**Comment by dirk-thomas** [comment]
That seems weird since I just confirmed that I see "all" rqt plugins after a fresh installation.

Please post the output of the following commands:
- dpkg -l | grep ros-indigo-rqt-
- source /opt/ros/indigo/setup.bash && rqt --list-plugins

**Comment by robotpilot** [comment]
Good, thank you for your kindness.

**Comment by dirk-thomas** [comment]
Does it mean that you were able to fix the issue? If yes it would be good if you comment how you were able to resolve it - in case others run into similar issues in the future they find the information here.

**Comment by robotpilot** [comment]
I don't know. 
Today morning, I just run "sudo apt-get update && upgrade" and restart my computer. 
then, the problem is resolved. I try on other pc. thanks.
